[install]
globalStore = false # TODO: Enable after https://github.com/oven-sh/bun/issues/36795 is fixed.
linker = "isolated"
minimumReleaseAge = 86400

[run]
bun = true

[test]
pathIgnorePatterns = ["apps/e2e/**"]
