/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as WidgetPreviewRouteImport } from './routes/widget-preview'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as DashboardAgentsRouteImport } from './routes/dashboard/agents'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardInvitationsRouteImport } from './routes/dashboard/invitations'
import { Route as DashboardAgentAgentIdRouteImport } from './routes/dashboard/agent.$agentId'
import { Route as DashboardWidgetsIndexRouteImport } from './routes/dashboard/widgets/index'
import { Route as DashboardWidgetsWidgetIdRouteImport } from './routes/dashboard/widgets/$widgetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetPreviewRoute = WidgetPreviewRouteImport.update({
  id: '/widget-preview',
  path: '/widget-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInvitationsRoute = DashboardInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAgentAgentIdRoute = DashboardAgentAgentIdRouteImport.update({
  id: '/agent/$agentId',
  path: '/agent/$agentId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWidgetsIndexRoute = DashboardWidgetsIndexRouteImport.update({
  id: '/widgets/',
  path: '/widgets/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWidgetsWidgetIdRoute =
  DashboardWidgetsWidgetIdRouteImport.update({
    id: '/widgets/$widgetId',
    path: '/widgets/$widgetId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/widget-preview': typeof WidgetPreviewRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/agent/$agentId': typeof DashboardAgentAgentIdRoute
  '/dashboard/widgets/$widgetId': typeof DashboardWidgetsWidgetIdRoute
  '/dashboard/widgets/': typeof DashboardWidgetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/widget-preview': typeof WidgetPreviewRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/agent/$agentId': typeof DashboardAgentAgentIdRoute
  '/dashboard/widgets/$widgetId': typeof DashboardWidgetsWidgetIdRoute
  '/dashboard/widgets': typeof DashboardWidgetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/widget-preview': typeof WidgetPreviewRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/agent/$agentId': typeof DashboardAgentAgentIdRoute
  '/dashboard/widgets/$widgetId': typeof DashboardWidgetsWidgetIdRoute
  '/dashboard/widgets/': typeof DashboardWidgetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/accept-invite'
    | '/invitations'
    | '/login'
    | '/setup'
    | '/widget-preview'
    | '/dashboard/account'
    | '/dashboard/agents'
    | '/dashboard/analytics'
    | '/dashboard/invitations'
    | '/dashboard/'
    | '/dashboard/agent/$agentId'
    | '/dashboard/widgets/$widgetId'
    | '/dashboard/widgets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/invitations'
    | '/login'
    | '/setup'
    | '/widget-preview'
    | '/dashboard/account'
    | '/dashboard/agents'
    | '/dashboard/analytics'
    | '/dashboard/invitations'
    | '/dashboard'
    | '/dashboard/agent/$agentId'
    | '/dashboard/widgets/$widgetId'
    | '/dashboard/widgets'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/accept-invite'
    | '/invitations'
    | '/login'
    | '/setup'
    | '/widget-preview'
    | '/dashboard/account'
    | '/dashboard/agents'
    | '/dashboard/analytics'
    | '/dashboard/invitations'
    | '/dashboard/'
    | '/dashboard/agent/$agentId'
    | '/dashboard/widgets/$widgetId'
    | '/dashboard/widgets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  InvitationsRoute: typeof InvitationsRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  WidgetPreviewRoute: typeof WidgetPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget-preview': {
      id: '/widget-preview'
      path: '/widget-preview'
      fullPath: '/widget-preview'
      preLoaderRoute: typeof WidgetPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/agents': {
      id: '/dashboard/agents'
      path: '/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/invitations': {
      id: '/dashboard/invitations'
      path: '/invitations'
      fullPath: '/dashboard/invitations'
      preLoaderRoute: typeof DashboardInvitationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/agent/$agentId': {
      id: '/dashboard/agent/$agentId'
      path: '/agent/$agentId'
      fullPath: '/dashboard/agent/$agentId'
      preLoaderRoute: typeof DashboardAgentAgentIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/widgets/': {
      id: '/dashboard/widgets/'
      path: '/widgets'
      fullPath: '/dashboard/widgets/'
      preLoaderRoute: typeof DashboardWidgetsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/widgets/$widgetId': {
      id: '/dashboard/widgets/$widgetId'
      path: '/widgets/$widgetId'
      fullPath: '/dashboard/widgets/$widgetId'
      preLoaderRoute: typeof DashboardWidgetsWidgetIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAgentsRoute: typeof DashboardAgentsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardInvitationsRoute: typeof DashboardInvitationsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAgentAgentIdRoute: typeof DashboardAgentAgentIdRoute
  DashboardWidgetsWidgetIdRoute: typeof DashboardWidgetsWidgetIdRoute
  DashboardWidgetsIndexRoute: typeof DashboardWidgetsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAgentsRoute: DashboardAgentsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardInvitationsRoute: DashboardInvitationsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAgentAgentIdRoute: DashboardAgentAgentIdRoute,
  DashboardWidgetsWidgetIdRoute: DashboardWidgetsWidgetIdRoute,
  DashboardWidgetsIndexRoute: DashboardWidgetsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  InvitationsRoute: InvitationsRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  WidgetPreviewRoute: WidgetPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
