import { sql } from "@/db/client.ts"

import * as repo from "./widget.repository.ts"
import * as service from "./widget.service.ts"

/**
 * Fixed so the E2E host-page fixture can embed a known widget. Real tokens are
 * random (`generateOpaqueToken`); this one exists only in the seeded test database.
 */
export const E2E_WIDGET_TOKEN = "e2e-marketing-widget-token"

export const E2E_WIDGET_PRIMARY = "#7c3aed"

export async function reset(): Promise<void> {
	await sql`TRUNCATE TABLE widget CASCADE`
}

export async function seed(agentId: string): Promise<{ publicToken: string }> {
	const marketing = await service.createWidget({
		agentId,
		name: "Marketing site",
		appearance: { primary: E2E_WIDGET_PRIMARY, primaryForeground: "#ffffff" },
	})
	// The token is generated by the service; pin it afterwards so the fixture can be
	// static without the service growing a test-only parameter.
	await repo.setPublicToken(marketing.id, E2E_WIDGET_TOKEN)

	await service.createWidget({ agentId, name: "Support portal", appearance: { position: "bottom-left" } })

	return { publicToken: E2E_WIDGET_TOKEN }
}
